### ISSUE TITLE
Why not put ASC in player controller?

### ISSUE THREAD

**Issue by RemRemRemRe** [tranek/GASDocumentation#31] opened 2020-08-01 16:18 UTC
Thanks for this great documentation about GAS.

Sorry, I can't find a way to contact you, so I opened this issue.

**Why it it is recommended to put ASC in player state instead of player controller?**

> If your Actor will respawn and need persistence of Attributes or GameplayEffects between spawns (like a hero in a MOBA), then the ideal location for the ASC is on the PlayerState.

Player controller can also support "respawn persistence", and it don't need to adjust the NetUpdateFrequency.

> Note: If your ASC is on your PlayerState, then you will need to increase the NetUpdateFrequency of your PlayerState. It defaults to a very low value on the PlayerState and can cause delays or perceived lag before changes to things like Attributes and GameplayTags happen on the clients. Be sure to enable Adaptive Network Update Frequency, Fortnite uses it.

So, I am curious about the reason behind this.

**Comment by tranek** [comment] 2020-08-01 17:59
> Sorry, I can't find a way to contact you, so I opened this issue.

The best place to ask GAS questions is on the [Unreal Slackers Discord Server](https://unrealslackers.org/). There's a channel just for GAS - #gameplay-abilities-plugin

> Why it it is recommended to put ASC in player state instead of player controller?

In multiplayer, the PlayerController isn't available to other clients. Generally you want to see how much health someone else has. The purpose of the PlayerState is to hold the "state" of the player, meaning the things that we use attributes for. Alternatively, you can put the ASC on the pawn and just not destroy the pawn on death.

In single player it doesn't matter as long as it functions correctly.


Issue is being closed as it's not a bug / issue with the code or the README. Please use the Discord or the official Unreal Engine forums for questions on how to use GAS.

**Closed by tranek** 2020-08-01 17:59 UTC
